### ISSUE TITLE
Tasks To Do

### ISSUE THREAD

**Issue by AnirudhG07** [AnirudhG07/custom-shell.yazi#11]
This is a few tasks todo to fix custom-shell.yazi and make it better
- [x] Fix the `confirm` and `interactive` API Reference [#1982](https://github.com/sxyazi/yazi/pull/1982)
- [ ] Fix for #4 i.e. supporting $0, etc
- [x] Fix the `--wait` issue as dicussed in #10, Tagging also #7

**Comment by pirafrank** [comment]
Hi, adding the following to the reference list. It might help.

https://github.com/sxyazi/yazi/issues/1772

**Comment by pirafrank** [comment]
Putting yazi in debug shows the `job.args` structure is different than it used to be (I am trying to find references to support this in docs/yazi 0.4.x migration issues).
It looks like now it's a table.

```
  2024-12-28T17:12:39.847271Z ERROR yazi_plugin::utils::log: {
  [1] = "zsh",
  wait = true,
}
```

thus `job.args[2]` returns `nil` for a setup like this:

```
{ on   = "!", run  = "plugin custom-shell --args='zsh --wait'" },
```

And it looks like this

```
  2024-12-28T17:22:39.945056Z ERROR yazi_plugin::utils::log: ">>>" {
  [1] = "zsh",
  no_block = true,
  no_confirm = true,
  orphan = true,
}
```

for config `run = "plugin custom-shell --args='zsh --no-block --orphan --no-confirm'" },`

So I guess, we need to either change the declaring syntax of options or the if statements to check for them.

edit: add more setup examples

**Comment by pirafrank** [comment]
I found reference for the new behaviour for shell-style args passed to plugins: https://yazi-rs.github.io/docs/plugins/overview/#functional-plugin.

It seems it has been introduced with version `0.4.0` (pre-0.4.0 version of the website had a different reference https://web.archive.org/web/20240921023453/https://yazi-rs.github.io/docs/plugins/overview/)

**Comment by pirafrank** [comment]
I found reference for the new behaviour for shell-style args passed to plugins: https://yazi-rs.github.io/docs/plugins/overview/#functional-plugin.

It seems it has been introduced with version `0.4.0` (pre-0.4.0 version of the website had a different reference https://web.archive.org/web/20240921023453/https://yazi-rs.github.io/docs/plugins/overview/)

![image](https://github.com/user-attachments/assets/8246e607-a22c-42d4-a4de-09ff5c397a6a)

**Comment by AnirudhG07** [comment]
I see, we ll have to change a lot here. Thanks for the references.

**Comment by pirafrank** [comment]
Well, there are changes, but the new structure should make the code clearer. I will try to submit a PR on Monday if I get some spare time for testing.

**Comment by AnirudhG07** [comment]
Ill also get on some work done by today(whenever ill have time too), hopefully you can add on to it. Thanks!

**Comment by AnirudhG07** [comment]
Check out #12, I have fixed the args issue at the time of this msg. Will be fixing more soon!

**Comment by AnirudhG07** [comment]
@pirafrank can you test the plugin based on commits on the PR. they work fine on my end.
I think things are good to go!
